#!/usr/bin/env bash

___pacman-sh() {
    local cur=${COMP_WORDS[COMP_CWORD]}

    case $COMP_CWORD in
      1)
        COMPREPLY=( $(compgen -W "list" -- "$cur") )
      ;;
      2)
        [[ ${COMP_WORDS[COMP_CWORD-1]} = @(list) ]] &&
          COMPREPLY=( $(compgen -W "orphans" -- "$cur") )
      ;;
    esac
}

complete -F ___pacman-sh pacman-sh
